# Change these first
owner: d-0-c
repo: git_mon

sites:
  - name: wta-suhl.de
    url: https://wta-suhl.de
  - name: demski-recycling.de
    url: https://demski-recycling.de
  - name: demski-recycling.com
    url: https://demski-recycling.com
  - name: einfach-verantwortungsvoll.de
    url: https://einfach-verantwortungsvoll.de
  - name: mygreentoner.de
    url: https://mygreentoner.de
  - name: mygreenprotector.de
    url: https://mygreenprotector.de

status-website:
  baseUrl: /git_mon
  logoUrl: https://wta-suhl.de/wp-content/uploads/2016/03/WTA-Suhl_Logo.png
  name: Website Status
  robotsText: "User-agent: * \n Disallow: /"
  theme: dark
  navbar:
    - title: Website Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  activeIncidents: aktuelle Vorfälle
  incidentReport: "Vorfall #$NUMBER Bericht →"
  activeIncidentSummary: Geöffnet am $DATE mit $POSTS Beiträgen
  incidentTitle: Vorfall $NUMBER Details
  incidentDetails: Vorfall Details
  incidentFixed: Behoben
  incidentOngoing: Laufend
  incidentOpenedAt: Geöffnet am
  incidentClosedAt: Geschlossen am
  incidentViewOnGitHub: auf GitHub verfolgen
  incidentCommentSummary: Veröffentlicht am $DATE von $AUTHOR
  incidentBack: ← Zurück zu allen Vorfällen
  pastIncidents: Vergangene Vorfälle
  pastIncidentsResolved: Gelöst in $MINUTES Minuten mit $POSTS Beiträgen
  liveStatus: Echtzeit Status
  overallUptime: "Verfügbarkeit: $UPTIME"
  overallUptimeTitle: Verfügbarkeit
  averageResponseTime: "Durchschnittliche Antwortzeit: $TIMEms"
  averageResponseTimeTitle: Durchschnittliche Antwortzeit
  sevelDayResponseTime: 7 Tage Antwortzeit
  responseTimeMs: Antwortzeit (ms)
  ms: ms
  loading: Läd
  navGitHub: GitHub
  # footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Rate limit exceeded
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: An error occurred
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: You can try again in a few moments.
  errorHome: Go to the homepage
  pastScheduledMaintenance: Past Scheduled Maintenance
  scheduledMaintenance: Scheduled Maintenance
  scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes
  scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
  startedAt: Gestartet am
  startsAt: Startet am
  duration: Dauer
  durationMin: $DURATION Minuten
  incidentCompleted: Fertig
  incidentScheduled: Geplant
  duration24H: 24 Std.
  duration7D: 7 Tage
  duration30D: 30 Tage
  duration1Y: 1 Jahr
  durationAll: "∞"
  # for readme:
  url: "URL"
  status: "Status"
  history: "Verlauf"
  responseTime: "Antwortzeit"
  uptime: "Verfügbarkeit"
  responseTimeGraphAlt: "Antwortzeit Graph"
  responseTimeDay: "24 Std. Antwortzeit"
  responseTimeWeek: "7 Tage Antwortzeit"
  responseTimeMonth: "30 Tage Antwortzeit"
  responseTimeYear: "1 Jahr Antwortzeit"
  uptimeDay: "24 Std. Verfügbarkeit"
  uptimeWeek: "7 Tage Verfügbarkeit"
  uptimeMonth: "30 Tage Verfügbarkeit"
  uptimeYear: "1 Jahr Verfügbarkeit"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "🟩 Alle Systeme Verfügbar"
  degradedPerformance: "🟨 Degradiert"
  completeOutage: "🟥 kompletter Ausfall"
  partialOutage: "🟧 partialer Ausfall"
